### ISSUE TITLE
不管是arm还是amd64的镜像，作者的也好，自己打包的也好，首页的热门影视只在刚加载的时候显示，然后就隐藏了

### ISSUE THREAD

**Issue by JianGangLi** [unilei/aipan-netdisk-search#78]
https://github.com/user-attachments/assets/071c3c23-9c11-408f-99f4-5c0f94f8c790

详情看视频，我用arm和x86设备都是这样的。但是看作者案例的网站是显示的。

docker日志
stdout: Running database migrations...
stdout: Prisma schema loaded from prisma/schema.prisma
stdout: Datasource "db": PostgreSQL database "aipan", schema "public" at "172.18.0.1:5432"
stdout: 
stdout: 5 migrations found in prisma/migrations
stdout: 
stdout: 
stdout: No pending migrations to apply.
stdout: Starting application...
stdout: Listening on http://[::]:3000
stdout: FetchError: [GET] "https://movie.douban.com/j/search_subjects?type&tag=%E7%83%AD%E9%97%A8&page_limit=24&page_start=0": <no response> fetch failed
stdout:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
stdout:     at async $fetchRaw2 (file:///app/.output/server/chunks/nitro/nitro.mjs:3902:14)
stdout:     ... 3 lines matching cause stack trace ...
stdout:     at async Server.toNodeHandle (file:///app/.output/server/chunks/nitro/nitro.mjs:3401:7) {
stdout:   [cause]: TypeError: fetch failed
stdout:       at node:internal/deps/undici/undici:12618:11
stdout:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
stdout:       at async $fetchRaw2 (file:///app/.output/server/chunks/nitro/nitro.mjs:3890:26)
stdout:       at async $fetchRaw2 (file:///app/.output/server/chunks/nitro/nitro.mjs:3902:14)
stdout:       at async $fetch2 (file:///app/.output/server/chunks/nitro/nitro.mjs:3948:15)
stdout:       at async Object.handler (file:///app/.output/server/chunks/routes/api/douban/new.mjs:17:15)
stdout:       at async Object.handler (file:///app/.output/server/chunks/nitro/nitro.mjs:3130:19)
stdout:       at async Server.toNodeHandle (file:///app/.output/server/chunks/nitro/nitro.mjs:3401:7) {
stdout:     cause: Error: connect ECONNREFUSED 120.53.130.158:443
stdout:         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
stdout:       errno: -111,
stdout:       code: 'ECONNREFUSED',
stdout:       syscall: 'connect',
stdout:       address: '120.53.130.158',
stdout:       port: 443
stdout:     }
stdout:   }
stdout: }

**Comment by JianGangLi** [comment]
我在研究研究，docker容器内无法ping通。

**Comment by JianGangLi** [comment]
容器可以访问外网，数据库也没出错，但是还是无法显示首页的内容
![image](https://github.com/user-attachments/assets/c4739ad3-6e95-4ce7-aad7-f2e9b007ca8e)
![image](https://github.com/user-attachments/assets/f1efd95c-62a9-4436-8744-c39450e62cc9)

**Comment by JianGangLi** [comment]
发现问题了，chrome 不知道为什么就是会隐藏，但是作者部署的那个不会。 edge浏览器会显示，现在不知道怎么解决。
![image](https://github.com/user-attachments/assets/658b6f18-d393-4836-a378-dc3fe48cbc56)
