### ISSUE TITLE
Docker 和 Vercel都无法成功部署

### ISSUE THREAD

**Issue by snoopytl** [unilei/aipan-netdisk-search#96]
1.我在我的云服务器部署，安装了docker，命令行也能看到我已经安装docker，但执行脚本时报错
![image](https://github.com/user-attachments/assets/67408c1e-283d-4567-97c4-87b2f3ccbfe9)

2.在vercel部署，严格按照部署步骤执行，也是报错

Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.

Learn how: https://pris.ly/d/vercel-build
PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.

Learn how: https://pris.ly/d/vercel-build
    at $a (/var/task/node_modules/@prisma/client/runtime/library.js:33:69)
    at new t (/var/task/node_modules/@prisma/client/runtime/library.js:130:739)
    at file:///var/task/chunks/nitro/nitro.mjs:6625:16
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async d (/opt/rust/nodejs.js:9:18812) {
  clientVersion: '6.0.0',
  errorCode: undefined
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.

到底该怎么玩

**Comment by chxsamidare** [comment]
兄弟你咋这么实诚呢？不会nano或者vi一下install.sh文件，把检测docker的命令注释掉不就行了 第15-25行全用#注释掉就行了

**Comment by snoopytl** [comment]
> 兄弟你咋这么实诚呢？不会nano或者vi一下install.sh文件，把检测docker的命令注释掉不就行了 第15-25行全用#注释掉就行了

就是纯小白啥也不懂啊

**Comment by flyer5048** [comment]
> > 兄弟你咋这么实诚呢？不会nano或者vi一下install.sh文件，把检测docker的命令注释掉不就行了 第15-25行全用#注释掉就行了
> 
> 就是纯小白啥也不懂啊

在install.sh文件中去掉Docker检查。保存后重新运行脚本。
```
check_requirements() {
    if ! command -v docker &> /dev/null; then
        print_message "Error: Docker is not installed!" "${RED}"
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null; then
        print_message "Error: Docker Compose is not installed!" "${RED}"
        exit 1
    fi
}
```
![image](https://github.com/user-attachments/assets/9b0ad01d-7391-4487-9e00-4e8e9d833673)
